### ISSUE TITLE
Is there a way to copy files from sshfs to local machine

### ISSUE THREAD

**Issue by KaustubhPatange** [nosduco/remote-sshfs.nvim#19]
I'm looking for a way to copy files from/to nvim sshfs connection to my local machine. Is this possible with the plugin? 

Asking because currently I don't see an option to achieve this.

**Comment by nosduco** [comment]
Do you happen to use a directory tree like NvimTree or Neotree? Or something like Oil? Since the directory is a file system mount and your Neovim instance should have it's "current working directory" set to that mount, any file operations in Neovim should persist to the remote filesystem and vice versa with the local.

**Comment by nosduco** [comment]
@KaustubhPatange Additionally, if you want to access the mount outside of Neovim it will be at the default mount directory (unless you changed it) `~/.sshfs/`

**Comment by KaustubhPatange** [comment]
Thanks for replying, it was an issue from my side. I failed to understand what sshfs does as it mounts the remote directory to my machine I can do any operation as I would be able to normally.

Thanks for clarifying, appreciated your work on this plugin.
