### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by ohdearaugustin** [nosduco/remote-sshfs.nvim#23]
The plugin doesn't consider wildcard in ssh/config.

I have following configuration:

```
Host exx--example
  Hostname 10.10.10.10

Host exx_ exx-*
  User root
  IdenityFile ~/.ssh/key
  ForwardAgent no
```

The plugin then tries to connect to the host with my current username and ask for a password.

If I add the settings directly to the host like:

```
Host exx--example
  Hostname 10.10.10.10
  User root
  IdenityFile ~/.ssh/key
  ForwardAgent no
```

Everything works as expected and the key is also loaded from the ssh-agent. I need this kind of a setup as I have over 200 hosts in my configuration and the with the wildcard my config is already 1200 lines long.

Edit:
I guess the function [parse_hosts_from_configs](https://github.com/nosduco/remote-sshfs.nvim/blob/e335a7a33ea1115ca6aa860e9f510ca8caf65833/lua/remote-sshfs/utils.lua#L52) would needed to be extended to support this use-case.

**Comment by nosduco** [comment]
@ohdearaugustin Thanks for the issue report!

This is an interesting one because the plugin itself doesn't pass the SSH opts (other than `Port`, `User`, and `Path`) from the host files specifically, it banks on the executables themselves to read from the SSH config for the specified host. etc, if you do `ssh <host>`  in your terminal, if the wildcards work they theoretically should work with the plugin as well... 

Maybe what is happening here is because you don't have `User` defined for the individual hosts, then https://github.com/nosduco/remote-sshfs.nvim/blob/main/lua/remote-sshfs/connections.lua#L109 this line is overwriting it with your local user which is incorrect and thus asking for your password. 

I'm debating on the best way to "detect" that it should not overwrite the username and use a different or wildcard one. Could be a configuration option, or potentially parse the SSH config files for any wildcards that match the current host and check if a `User` is specified. Probably would do that for `Port` and `Path` as well... 

Open to suggestions! Will try and tinker with this today and early this week.

**Comment by nosduco** [comment]
https://github.com/libfuse/sshfs?tab=readme-ov-file#how-to-use

With how SSHFS works under the hood, seems like parsing for the wildcard configuration and using the `User` (and other options) from that is the only way since SSHFS defaults to local user if not supplied...

**Comment by ohdearaugustin** [comment]
I have now tried it with sshfs itself and it seems like to work with the wildcard.

I guess the best approach would be to not fallback on the local user in the lua script. This way we would not need to parse the whole ssh config in lua. Furthermore if no user is defined in the plugin or the ssh config sshfs automatically will fallback to the local user anyway.
