### ISSUE TITLE
The default path is hard-coded to "{user}@{host}:/home/{user}"

### ISSUE THREAD

**Issue by jrjsmrtn** [nosduco/remote-sshfs.nvim#9]
The default path is hard-coded to "{user}@{host}:/home/{user}", preventing some home directories to be mounted:
- root (/root)
- macOS users (in /Users/{user})

**Comment by MisterSincere** [comment]
I had the same problem since I am connecting to a host with an AFS running, so the std user dir isn't existing and my connection failed.
Upon further inspection it is not completely hard coded and it actually tries to use the custom ssh config field "Path" and uses that one if set instead. But I had a problem adding that field in my ssh config file, since sshfs uses ssh under the hood and hence crashed complaining about an invalid config file.
So what I do now is setting the field my self after plugin setup:
`require('remote-sshfs.connections').list_hosts()["<your_host>"]["Path"] = "<custom_dir>"`

If there is an easier way somewhere in the setup of the plugin I did not find it though.

**Comment by jrjsmrtn** [comment]
@MisterSincere I had the same issue with the `Path` argument in the `ssh_config` file: it's not recognised by my main SSH client (OpenSSH_9.0p1, LibreSSL 3.3.6)
